import type { PreviewData } from "../shared/types";

export const previewData: PreviewData = {
  metrics: [
    {
      label: "总资产",
      value: "¥ 286,420.36",
      comparison: "累计收益 +18,642.17",
      trend: "positive",
    },
    { label: "当日预估收益", value: "+ ¥ 1,284.20", comparison: "+0.45%", trend: "positive" },
    { label: "持仓成本", value: "¥ 267,778.19", comparison: "8 只基金", trend: "neutral" },
    { label: "沪深 300", value: "4,071.68", comparison: "-0.24%", trend: "negative" },
  ],
  holdings: [
    {
      id: "h1",
      fundCode: "161725",
      fundName: "招商中证白酒指数",
      shares: "12,842.31",
      costNav: "1.1264",
      currentNav: "1.1842",
      marketValue: "15,207.04",
      dailyChange: "+0.62%",
      dailyPnl: "+91.32",
      cumulativePnl: "+742.27",
      openedOn: "2024-03-15",
      version: 1,
    },
    {
      id: "h2",
      fundCode: "005827",
      fundName: "易方达蓝筹精选混合",
      shares: "28,100.00",
      costNav: "1.7821",
      currentNav: "1.7054",
      marketValue: "47,921.74",
      dailyChange: "-0.18%",
      dailyPnl: "-86.26",
      cumulativePnl: "-2,155.27",
      openedOn: "2024-05-08",
      version: 1,
    },
    {
      id: "h3",
      fundCode: "110011",
      fundName: "易方达中小盘混合",
      shares: "19,420.68",
      costNav: "4.2836",
      currentNav: "4.6120",
      marketValue: "89,566.98",
      dailyChange: "+0.91%",
      dailyPnl: "+812.04",
      cumulativePnl: "+6,378.75",
      openedOn: "2023-11-20",
      version: 1,
    },
  ],
  instruments: [
    {
      id: "i1",
      code: "000001.SH",
      name: "上证指数",
      assetType: "index",
      market: "sh",
      providerId: "eastmoney",
    },
    {
      id: "i2",
      code: "IXIC",
      name: "纳斯达克",
      assetType: "index",
      market: "us",
      providerId: "eastmoney",
    },
    {
      id: "i3",
      code: "600519.SH",
      name: "贵州茅台",
      assetType: "stock",
      market: "sh",
      providerId: "eastmoney",
    },
    {
      id: "i4",
      code: "USD/CNY",
      name: "美元 / 人民币",
      assetType: "fx",
      market: "us",
      providerId: "eastmoney",
    },
    { id: "i5", code: "XAU", name: "伦敦金", assetType: "metal", market: "us", providerId: "eastmoney" },
  ],
  quotes: [
    {
      instrument: {
        id: "i1",
        code: "000001.SH",
        name: "上证指数",
        assetType: "index",
        market: "sh",
        providerId: "eastmoney",
      },
      price: "3,665.92",
      change: "+0.34%",
      open: "3,655.10",
      high: "3,672.44",
      low: "3,648.30",
      previousClose: "3,653.51",
      volume: "412.5亿",
      amount: "5,410.2亿",
    },
    {
      instrument: {
        id: "i2",
        code: "IXIC",
        name: "纳斯达克",
        assetType: "index",
        market: "us",
        providerId: "eastmoney",
      },
      price: "21,713.14",
      change: "+0.14%",
      open: "21,688.20",
      high: "21,745.88",
      low: "21,662.10",
      previousClose: "21,682.80",
      volume: "4.8亿",
      amount: "—",
    },
    {
      instrument: {
        id: "i3",
        code: "600519.SH",
        name: "贵州茅台",
        assetType: "stock",
        market: "sh",
        providerId: "eastmoney",
      },
      price: "1,428.20",
      change: "-0.72%",
      open: "1,438.00",
      high: "1,441.50",
      low: "1,424.80",
      previousClose: "1,438.56",
      volume: "3.2万手",
      amount: "45.6亿",
    },
  ],
  plans: [
    {
      id: "p1",
      fundCode: "110020",
      fundName: "易方达沪深300ETF联接",
      amount: "1500.00",
      frequency: "monthly",
      executionDay: 15,
      startDate: "2026-01-15",
      status: "active",
      version: 1,
    },
    {
      id: "p2",
      fundCode: "160119",
      fundName: "南方中证500ETF联接",
      amount: "500.00",
      frequency: "weekly",
      executionDay: 4,
      startDate: "2026-02-05",
      status: "paused",
      version: 1,
    },
  ],
  news: [
    {
      id: "n1",
      title: "主要指数午后窄幅震荡，成交额较前一交易日收缩",
      publishedAt: "15:42",
      source: "东方财富",
      url: "https://finance.eastmoney.com/",
      tag: "市场",
    },
    {
      id: "n2",
      title: "公开市场操作保持流动性合理充裕",
      publishedAt: "15:18",
      source: "东方财富",
      url: "https://finance.eastmoney.com/",
      tag: "宏观",
    },
    {
      id: "n3",
      title: "半导体与医药板块表现分化",
      publishedAt: "14:56",
      source: "东方财富",
      url: "https://finance.eastmoney.com/",
      tag: "行业",
    },
  ],
};
